# Generated by Django 5.0.2 on 2025-07-12 18:25

import django.contrib.gis.db.models.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hotel"),
                            ("museum", "Museum"),
                            ("park", "Park"),
                            ("shopping", "Shopping"),
                            ("transport", "Transport"),
                            ("landmark", "Landmark"),
                            ("entertainment", "Entertainment"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        db_index=True,
                        help_text="Geographic coordinates (longitude, latitude)",
                        srid=4326,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pois",
                "indexes": [
                    models.Index(
                        fields=["category", "created_at"],
                        name="pois_categor_1ccf01_idx",
                    ),
                    models.Index(
                        fields=["rating", "category"], name="pois_rating_5b96a2_idx"
                    ),
                ],
            },
        ),
    ]
